#import lib.plantoid.behaviors.behavior_library as behavior_library
from lib.plantoid.behaviors import behavior_library
#from plantoids.plantoid import Plantony
import lib.plantoid.eden as eden
import lib.plantoid.speech as PlantoidSpeech

import os
from dotenv import load_dotenv
from pinata import Pinata
load_dotenv()

PINATA_API_KEY = os.environ.get("PINATA_API_KEY")
PINATA_API_SECRET = os.environ.get("PINATA_API_SECRET")
PINATA_JWT = os.environ.get('PINATA_JWT')



def ingurgitate_crypto(plantoid, network, tID, amount):

    credits = int(amount / network.min_amount)  

    # do weaving : ask "what future are you dreaming of ?"
    plantoid.weaving()
        
    # listen for audio and obtain the transcript
    user_speech = plantoid.listen() or behavior_library.get_default_transcript(plantoid.plantoid_number, plantoid.lang)

    print("I heard ..", user_speech)  
    
    behavior_library.archive("text", "transcript", user_speech, tID, network)

    # Generate response
    plantoid.send_serial_message("thinking")

    prompt = behavior_library.get_prompt(plantoid.plantoid_number, user_speech, plantoid.selected_words_string, credits, plantoid.lang)

    response_text = PlantoidSpeech.GPTmagic(prompt, model=plantoid.llm_model)
    print('response text: ', response_text)

    # generate, print, and read the oracle
    # oracle = behavior_library.generate_oracle(plantoid, network, audiofile, tID, amount)

    behavior_library.archive("text", "response", response_text, tID, network)

    # print oracle on the LP printer
    behavior_library.print_response(plantoid, network, tID, response_text)

    # generate audio file
    audiofile = PlantoidSpeech.stream_response(plantoid, response_text, plantoid.voice_id, save_to_file="/tmp/output_oracle.wav")

    # convert to .mp3
    import subprocess
    mp3_file = "/tmp/output_oracle.mp3"
    subprocess.run(["ffmpeg", "-y", "-i", audiofile, mp3_file])
    audiofile = mp3_file


    # read oracle out loud
    # behavior_library.read_oracle(plantoid, network, tID, oracle)

    plantoid.send_serial_message("awake")

    # save and play the oracle
    behavior_library.save_and_play_audio(plantoid, network, tID, audiofile)



def create_seed_metadata(plantoid, network, token_Id):

    movie_path = None
    animurl = None

    # create the metadata information
    db = dict()
    db['name'] = token_Id
    db['description'] = "Plantoid #14 - Seed #" + token_Id
    db['external_url'] = "http://plantoid.org"
    db['image'] = "https://ipfs.io/ipfs/QmRcrcn4X6QfSwFnJQ1dNHn8YgW7pbmm6BjZn7t8FW7WFV" # ipfsQpng



    # check if a movie exists for that particular token_Id

    path = network.plantoid_path
    if os.path.exists(path + "/videos/" + network.name + "/" + token_Id +"_movie.mp4"):
        movie_path = path + "/videos/" + network.name + "/" + token_Id +"_movie.mp4"

    elif os.path.isfile(path + "/audios/" + network.name + "/" + token_Id + "_audio.mp3"):

        # if movie doesn't exist, but sermon.mp3 exists, make a new movie based on the recorded audio:

        plantoid.send_serial_message("thinking")


        # launch the API call which will return the video generated by Eden
        # only if failsafe is not set (if set, it will recycle an existing movie).
    
        if(network.failsafe  == 0):

            print('generating video file with eden')

            #init_img = "https://edenartlab-prod-data.s3.us-east-1.amazonaws.com/c25c6b80c347d214eef34d67ee9b586f8e7de90662076667563f781c504f2877.webp"
            init_img = "https://edenartlab-prod-data.s3.us-east-1.amazonaws.com/6a964945ff55658132d450531220418427da6c82adeb6176a8a4d0782f92dab4.jpg"
            init_strength = 0.1
            movie_path = behavior_library.create_video_from_audio(path, token_Id, network.name, init_img, init_strength)

        
        elif(network.failsafe == 1 or movie_path == None):
            
            print('using failsafe, using fallback')
            #print("PlantoidEden.make_eden_API_call return Null -- going to use a fallback video !")
            movie_path = behavior_library.fallback_video(path, token_Id, network.name)
        
        
        movie_path = behavior_library.make_video(path, movie_path, token_Id, network.name)


    animurl = behavior_library.pin_movie(movie_path)
    
    if(animurl):  ## only upload metadata if there is an associated video
        behavior_library.record_metadata(plantoid, network, token_Id, db, animurl)

    plantoid.send_serial_message("awake") ## REMOVE







