from lib.plantoid.behaviors import behavior_library

import lib.plantoid.speech as PlantoidSpeech

import os
import re

from dotenv import load_dotenv
from pinata import Pinata
load_dotenv()

PINATA_API_KEY = os.environ.get("PINATA_API_KEY")
PINATA_API_SECRET = os.environ.get("PINATA_API_SECRET")
PINATA_JWT = os.environ.get('PINATA_JWT')



def ingurgitate_crypto(plantoid, network, tID, amount):

    question = "What is the song that you're weaving into being through your life?"
    user_speech = behavior_library.ask_transcript(plantoid, network, tID, question)


    # Generate response  ..
    plantoid.send_serial_message("thinking")
    
    # calculate the credits for the response
    # one line every 0.01 ETH for mainnet, one line every 0.001 ETH for goerli
    credits = int(amount / network.min_amount)  

    lines = behavior_library.get_song_prompts(plantoid, user_speech, credits)
    
    response = '\n'.join(lines)
    print('fixed response text: ', response)

    # archive the response
    behavior_library.archive("text", "response", response, tID, network)

    # print response on the LP printer
    behavior_library.print_response(plantoid, network, tID, response)
    
    # create a song
    audiofile = behavior_library.generate_song(lines, credits)


    plantoid.send_serial_message("awake")
    
    # save and play the song
    behavior_library.save_and_play_audio(plantoid, network, tID, audiofile)




def create_seed_metadata(plantoid, network, token_Id):

    movie_path = None
    animurl = None

    # create the metadata information

    db = dict()
    db['name'] = token_Id
    db['description'] = "Plantoid #16 - Seed #" + token_Id
    db['external_url'] = "http://plantoid.org"
    db['image'] = "https://ipfs.io/ipfs/bafybeihkwbsoy6rbkduezgqefddivk54pqgdbttz5r3gib64v5ysme4naa" # @@@ CHANGEEE


    # check if a movie exists for that particular token_Id

    path = network.plantoid_path
    if os.path.exists(path + "/videos/" + network.name + "/" + token_Id +"_movie.mp4"):
        movie_path = path + "/videos/" + network.name + "/" + token_Id +"_movie.mp4"

    elif os.path.isfile(path + "/audios/" + network.name + "/" + token_Id + "_audio.mp3"):

        # if movie doesn't exist, but song.mp3 exists, make a new movie based on the recorded audio:

        plantoid.send_serial_message("thinking")


        # launch the API call which will return the video generated by Eden
        # only if failsafe is not set (if set, it will recycle an existing movie).
    
        # if(network.failsafe  == 0):

        #     print('generating video file with eden')

        #     init_img = "https://d14i3advvh2bvd.cloudfront.net/b09558370b41681c92309f158d50999c0c01e13979ac1d9461bfe6b8cb0f215b_2560.webp"
        #     init_strength = 0
        #     movie_path = behavior_library.create_video_from_audio(path, token_Id, network.name, init_img, init_strength)

        
        # elif(network.failsafe == 1 or movie_path == None):
            
        #     print('using failsafe, using fallback')
        #     #print("PlantoidEden.make_eden_API_call return Null -- going to use a fallback video !")
        #     movie_path = behavior_library.fallback_video(path, token_Id, network.name)
        

        ## VISUALISATION GEN-ART on RASPBERRY
        # os.system('python3.10 ' + path + '/../lib/plantoid/behaviors/sound_visualisation.py ' + 
        #          path + "/audios/" + network.name + "/" + token_Id + "_audio.mp3" +
        #          " -o " + path + "/videos/" + network.name + "/" + token_Id + "_movie.mp4 " +
        #          " --size 800 --fps 24")
        
        from mutagen.mp3 import MP3

        glitchbox_server = "100.79.41.86" # GLITCHBOX on TAILSCALE
        glitchbox_path = path + '/../lib/plantoid/behaviors/glitchbox/'
        movie_path = path + "/videos/" + network.name + "/" + token_Id +"_movie.mp4"
        audio_mp3 = path + "/audios/" + network.name + "/" + token_Id + "_audio.mp3"
        init_img = glitchbox_path + 'input2.jpg'
        fps = "15"
        duration = MP3(audio_mp3).info.length
        loras = "21" # twisted bodies & water

        os.system('python3.10 ' + glitchbox_path + f"grpc_prompt_journey.py --server {glitchbox_server} --scheduler --fps {fps} --init-image {init_img} --audio {audio_mp3} --duration {duration} --curation {loras} --output {movie_path}" )

        # movie_path = behavior_library.make_video(path, movie_path, token_Id, network.name)


    animurl = behavior_library.pin_movie(movie_path)
    
    if(animurl):  ## only upload metadata if there is an associated video
        behavior_library.record_metadata(plantoid, network, token_Id, db, animurl)

    plantoid.send_serial_message("awake") ## REMOVE





