#import lib.plantoid.behaviors.behavior_library as behavior_library
from lib.plantoid.behaviors import behavior_library
#from plantoids.plantoid import Plantony
import lib.plantoid.eden as eden


import os
from dotenv import load_dotenv
from pinata import Pinata
load_dotenv()

PINATA_API_KEY = os.environ.get("PINATA_API_KEY")
PINATA_API_SECRET = os.environ.get("PINATA_API_SECRET")
PINATA_JWT = os.environ.get('PINATA_JWT')



def ingurgitate_crypto(plantoid, network, tID, amount):

    # calculate the credits for the response
    # one line every 0.01 ETH for mainnet, one line every 0.001 ETH for goerli
    credits = int(amount / network.min_amount)  

    # do weaving
    plantoid.weaving()
        
    # listen for audio
    audiofile = plantoid.listen()
    
    # generate the response ### NB: response is an array of lyrics
    response = behavior_library.generate_GPT_response("opera", plantoid, network, audiofile, tID, credits)

    # print response on the LP printer
    toprint = '\n'.join(response)
    behavior_library.print_response(plantoid, network, tID, toprint)

    
    # create a song
    audiofile = behavior_library.generate_song(response, credits)
    
    # save and play the song
    behavior_library.save_and_play_audio(plantoid, network, tID, audiofile)




def create_seed_metadata(plantoid, network, token_Id):

    movie_path = None
    animurl = None

    # create the metadata information

    db = dict()
    db['name'] = token_Id
    db['description'] = "Plantoid #16 - Seed #" + token_Id
    db['external_url'] = "http://plantoid.org"
    db['image'] = "https://ipfs.io/ipfs/bafybeihkwbsoy6rbkduezgqefddivk54pqgdbttz5r3gib64v5ysme4naa" # @@@ CHANGEEE


    # check if a movie exists for that particular token_Id

    path = network.plantoid_path
    if os.path.exists(path + "/videos/" + network.name + "/" + token_Id +"_movie.mp4"):
        movie_path = path + "/videos/" + network.name + "/" + token_Id +"_movie.mp4"

    elif os.path.isfile(path + "/audios/" + network.name + "/" + token_Id + "_audio.mp3"):

        # if movie doesn't exist, but song.mp3 exists, make a new movie based on the recorded audio:

        plantoid.send_serial_message("thinking")


        # launch the API call which will return the video generated by Eden
        # only if failsafe is not set (if set, it will recycle an existing movie).
    
        # if(network.failsafe  == 0):

        #     print('generating video file with eden')

        #     init_img = "https://d14i3advvh2bvd.cloudfront.net/b09558370b41681c92309f158d50999c0c01e13979ac1d9461bfe6b8cb0f215b_2560.webp"
        #     init_strength = 0
        #     movie_path = behavior_library.create_video_from_audio(path, token_Id, network.name, init_img, init_strength)

        
        # elif(network.failsafe == 1 or movie_path == None):
            
        #     print('using failsafe, using fallback')
        #     #print("PlantoidEden.make_eden_API_call return Null -- going to use a fallback video !")
        #     movie_path = behavior_library.fallback_video(path, token_Id, network.name)
        
        os.system('python3.10 ' + path + '/../lib/plantoid/behaviors/sound_visualisation.py ' + 
                  path + "/audios/" + network.name + "/" + token_Id + "_audio.mp3" +
                  " -o " + path + "/videos/" + network.name + "/" + token_Id + "_movie.mp4 " +
                  " --size 800 --fps 24")
        
        movie_path = path + "/videos/" + network.name + "/" + token_Id +"_movie.mp4"
        
        # movie_path = behavior_library.make_video(path, movie_path, token_Id, network.name)


    animurl = behavior_library.pin_movie(movie_path)
    
    if(animurl):  ## only upload metadata if there is an associated video
        behavior_library.record_metadata(plantoid, network, token_Id, db, animurl)

    plantoid.send_serial_message("awake") ## REMOVE





